# Generated by Django 4.2.5 on 2023-09-20 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_content_quizqanda_syllabus_quizes_material_faq_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='classschedule',
            options={'verbose_name_plural': 'Class Schedule'},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name_plural': 'Content'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name_plural': 'Course'},
        ),
        migrations.AlterModelOptions(
            name='enrollments',
            options={'verbose_name_plural': 'Enrollment'},
        ),
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name_plural': 'Faq'},
        ),
        migrations.AlterModelOptions(
            name='instructor',
            options={'verbose_name_plural': 'Instructor'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name_plural': 'Material'},
        ),
        migrations.AlterModelOptions(
            name='quizes',
            options={'verbose_name_plural': 'Quizes'},
        ),
        migrations.AlterModelOptions(
            name='quizqanda',
            options={'verbose_name_plural': 'QuizQandA'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name_plural': 'Student'},
        ),
        migrations.AlterModelOptions(
            name='syllabus',
            options={'verbose_name_plural': 'Syllabus'},
        ),
    ]
