# Generated by Django 4.2.5 on 2023-10-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmain', '0002_instructor_profilepicture_student_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='fileMaterial',
            field=models.FileField(blank=True, default=1, null=True, upload_to='video%y'),
        ),
    ]
